import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  helpSidebar: [
    'index',
    {type: 'category', label: 'Getting started', collapsed: false, items: [{type: 'autogenerated', dirName: 'getting-started'}]},
    {type: 'category', label: 'Our services', link: {type: 'doc', id: 'services/index'}, items: [{type: 'autogenerated', dirName: 'services'}]},
    {type: 'category', label: 'Client reports', items: [{type: 'autogenerated', dirName: 'reports'}]},
    {type: 'category', label: 'Healthcare and Abe', items: [{type: 'autogenerated', dirName: 'health-and-abe'}]},
    {type: 'category', label: 'Creating content', items: [{type: 'autogenerated', dirName: 'creating-content'}]},
    {type: 'category', label: 'Publishing and scheduling', items: [{type: 'autogenerated', dirName: 'publishing'}]},
    {type: 'category', label: 'Media and design', items: [{type: 'autogenerated', dirName: 'video-and-design'}]},
    {type: 'category', label: 'Your brand', items: [{type: 'autogenerated', dirName: 'your-brand'}]},
    {type: 'category', label: 'Eve and your AI', items: [{type: 'autogenerated', dirName: 'talking-to-director'}]},
    {type: 'category', label: 'Team and sharing', items: [{type: 'autogenerated', dirName: 'team-and-sharing'}]},
    {type: 'category', label: 'Connections and devices', items: [{type: 'autogenerated', dirName: 'connecting-devices'}]},
    {type: 'category', label: 'Advertising rules', items: [{type: 'autogenerated', dirName: 'compliance'}]},
    {type: 'category', label: 'Understanding results', items: [{type: 'autogenerated', dirName: 'understanding-reports'}]},
    {type: 'category', label: 'Accounts and billing', items: [{type: 'autogenerated', dirName: 'account-and-billing'}]},
    {type: 'category', label: 'Troubleshooting', items: [{type: 'autogenerated', dirName: 'troubleshooting'}]},
    {type: 'category', label: 'About Not Real Smart', items: [{type: 'autogenerated', dirName: 'about'}]},
  ],
};

export default sidebars;
