import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  helpSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Talking to Your Director',
      items: [{type: 'autogenerated', dirName: 'talking-to-director'}],
    },
    {
      type: 'category',
      label: 'Creating Content',
      items: [{type: 'autogenerated', dirName: 'creating-content'}],
    },
    {
      type: 'category',
      label: 'Publishing & Scheduling',
      items: [{type: 'autogenerated', dirName: 'publishing'}],
    },
    {
      type: 'category',
      label: 'Video & Design',
      items: [{type: 'autogenerated', dirName: 'video-and-design'}],
    },
    {
      type: 'category',
      label: 'Your Brand',
      items: [{type: 'autogenerated', dirName: 'your-brand'}],
    },
    {
      type: 'category',
      label: 'Team & Sharing',
      items: [{type: 'autogenerated', dirName: 'team-and-sharing'}],
    },
    {
      type: 'category',
      label: 'Use From Anywhere',
      items: [{type: 'autogenerated', dirName: 'connecting-devices'}],
    },
    {
      type: 'category',
      label: 'Staying Compliant',
      items: [{type: 'autogenerated', dirName: 'compliance'}],
    },
    {
      type: 'category',
      label: 'Understanding Reports',
      items: [{type: 'autogenerated', dirName: 'understanding-reports'}],
    },
    {
      type: 'category',
      label: 'Account & Billing',
      items: [{type: 'autogenerated', dirName: 'account-and-billing'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
  ],
};

export default sidebars;
